apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller deployment --out kubernetes/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  type: LoadBalancer
  ports:
    - name: 3306-tcp
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
