apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  type: LoadBalancer
  ports:
  - name: "web"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: web